### ISSUE TITLE
Soft Reboot

### ISSUE THREAD

**Issue by shortyishere** [ayufan-rock64/linux-build#127] opened 2018-03-09 05:01 UTC
Emmc corruption on soft reboot...cycle power boots ok...bionic latest 193

**Comment by vasekch** [comment] 2018-03-11 20:28
This happened to me even on SD also on older images 187
Hard reboot is somehow more reliable than soft reboot.
Not sure if the problem is corruption of the media, but something weird is going on there...

**Comment by vasekch** [comment] 2018-03-12 02:16
The same behaviour with xenial minimal 0.6.25 193 armhf updated to latest versions
`reboot` or `shutdown --reboot now` performs reboot, but lot of kernel failures are on screen during the boot, than it got stuck.
after power cycling all is ok

**Comment by vasekch** [comment] 2018-03-12 13:02
appending "screenshots" with failures after soft reboot
![image](https://user-images.githubusercontent.com/2572537/37285040-9f4cbafe-25f5-11e8-849a-59b6a54fd716.png)
![image](https://user-images.githubusercontent.com/2572537/37285060-a75e714c-25f5-11e8-9079-35bcec205c8b.png)

**Comment by S3phi40T** [comment] 2018-03-14 17:29
I can confirm the same behaviour with stretch OMV. 
soft reboot doesn't work. 
Power cycle via plug works OK.

**Comment by ayufan** [comment] 2018-03-29 21:32
But this happens since 0.6.25 as I can see. I don't see that problem before :)

**Comment by S3phi40T** [comment] 2018-03-30 08:14
Yes, since 0.6.25.

**Comment by ayufan** [comment] 2018-03-30 08:15
This is fixed in 0.6.28 :)

**Closed by ayufan** 2018-03-30 08:15 UTC

**Comment by S3phi40T** [comment] 2018-03-30 11:29
I have upgraded from 0.6.25 to 0.6.28.
No change.
Haven't tried clean install yet.

**Comment by ayufan** [comment] 2018-03-30 11:32
It requires clean install due to bootloader

**Comment by enekux** [comment] 2018-03-30 12:12
Me too, the upgrade does not directly fix the issue.
What does a clean install mean?
# apt remove --purge linux-rock64
# apt install linux-rock64

**Comment by ayufan** [comment] 2018-03-30 12:42
Different bootloader. You only change kernel. Not bootloader.

**Comment by S3phi40T** [comment] 2018-03-31 13:44
Clean install worked. :)

**Comment by ayufan** [comment] 2018-03-31 13:47
I will write later how to upgrade bootloader.

**Comment by enekux** [comment] 2018-03-31 13:55
@ayufan that would be great, thanks

**Comment by enekux** [comment] 2018-04-01 08:50
I see a new package there in the latest pre-release... ;)

Shall we install it?

# apt search u-boot-rock64
Sorting... Done
Full Text Search... Done
u-boot-rock64/unknown 0.6.29 all
  Rock64 U-boot package

**Comment by ayufan** [comment] 2018-04-01 08:50
Well. Download manually. And install.

**Comment by enekux** [comment] 2018-04-02 09:13
It works wonderfully.
Thank you very much.
