### ISSUE TITLE
kernel panic with -195 bionic

### ISSUE THREAD

**Issue by Pytheas54** [ayufan-rock64/linux-build#143] opened 2018-03-28 22:46 UTC
both after upgrading from a working -193 arm64 bionic and a fresh install of bionic-minimal-rock64-0.6.26-195-arm64.img.xz

**Comment by ayufan** [comment] 2018-03-29 09:36
Duplicate of https://github.com/ayufan-rock64/linux-build/issues/144

**Closed by ayufan** 2018-03-29 09:36 UTC
