### ISSUE TITLE
Ethernet is not working

### ISSUE THREAD

**Issue by fjoel** [ayufan-rock64/linux-build#44] opened 2017-09-22 12:25 UTC
Hello, 
thank you very much for the images! I use the xenial minimal image. My ethernet is not working with the 5.13 Xenial minimal image (rock64 board version 2.0). With ifconfig I get only:

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:20 errors:0 dropped:0 overruns:0 frame:0
          TX packets:20 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:1949 (1.9 KB)  TX bytes:1949 (1.9 KB)

It's possible to connect the rock64 board over USB3 ethernt adapter (ifconfig: enx00133b8945ba). Can you activate ethernet?

Regards,
F. Joel

**Comment by ayufan** [comment] 2017-09-22 12:54
Yes. Just do:

```
ifconfig enx00133b8945ba up
dhclient enx00133b8945ba
```

Or just add that to `/etc/network/interfaces`:

```
cat <<EOF > /etc/network/interfaces.d/usb3
auto enx00133b8945ba
iface enx00133b8945ba inet dhcp
```

and then:

```
ifup eth0
```

**Comment by ayufan** [comment] 2017-09-22 12:57
Duplicate off: https://github.com/ayufan-rock64/linux-build/issues/39

**Closed by ayufan** 2017-09-22 12:57 UTC
