### ISSUE TITLE
USB 3.0 unreliability

### ISSUE THREAD

**Issue by Omer811** [ayufan-rock64/linux-build#293] opened 2018-10-24 16:25 UTC
I have a problem with data transfer on an usb hub.
when under load, the usb connection the the drives that are connected to the hub crashes
https://pastebin.com/JGM3xKDz

the hub is a4 port powered hub by Anker, and two powered summing disks are connected to it
hub's lsusb - https://pastebin.com/MiAMh9K5
I'm running 4.4.154-1122-rockchip-ayufan-g7859b9b904a9
with OMV installed

i'v tried the following advice https://bbs.archlinux.org/viewtopic.php?id=183190 on comment #12, which helped a little, the drives became more stable, but disconnected after all.

**Comment by dkimmortal** [comment] 2019-02-18 04:07
Excited, briefly testing usb hub transfers that would previously crash with rsync, the new Manjaro-arm release seems to transfer fine SO FAR, on it less than 24 hours, need further testing, hope ayufan can take whatever it is that fixes it in the Manjaro release
Tested with simultaneously transferring from usb a to usb b and usb c to usb d all on the same hub connected to the usb3 port

**Comment by javaboyuk** [comment] 2019-03-24 19:49
running:
Linux rockpro64 4.4.167-1161-rockchip-ayufan-g6f1664023387 #1 SMP Fri Mar 22 23:03:38 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

doinf test:
time dd if=/dev/zero of=swap2g bs=1024 count=2097152

usb 2 works ok ~40MB/sec on small test 
but if I plug it into USB 3.0 it fails, when I try same test:
Mar 24 19:22:35 rockpro64 kernel: [   47.712519] EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts: (null)
Mar 24 19:29:10 rockpro64 systemd-timesyncd[395]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Mar 24 19:29:18 rockpro64 kernel: [   57.576936] usb 4-1: reset SuperSpeed USB device number 2 using xhci-hcd
Mar 24 19:29:30 rockpro64 kernel: [   69.147234] wl_run_escan: LEGACY_SCAN sync ID: 3, bssidx: 0
Mar 24 19:29:34 rockpro64 CRON[876]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)
Mar 24 19:29:49 rockpro64 kernel: [   88.103647] usb 4-1: reset SuperSpeed USB device number 2 using xhci-hcd
Mar 24 19:30:01 rockpro64 CRON[883]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)
Mar 24 19:30:01 rockpro64 systemd[1]: Started Session 7 of user root.
Mar 24 19:30:13 rockpro64 kernel: [  112.131154] wl_run_escan: LEGACY_SCAN sync ID: 4, bssidx: 0
Mar 24 19:30:20 rockpro64 kernel: [  119.074033] usb 4-1: reset SuperSpeed USB device number 2 using xhci-hcd
Mar 24 19:30:30 rockpro64 kernel: [  129.202231] usb 4-1: reset SuperSpeed USB device number 2 using xhci-hcd
Mar 24 19:30:35 rockpro64 kernel: [  134.942379] usb 4-1: USB disconnect, device number 2
Mar 24 19:30:35 rockpro64 kernel: [  134.957823] sd 0:0:0:0: Device offlined - not ready after error recovery
Mar 24 19:30:35 rockpro64 kernel: [  134.965603] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x01 driverbyte=0x00
Mar 24 19:30:35 rockpro64 kernel: [  134.965644] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x2a 2a 00 04 4b 94 b0 00 00 f0 00
Mar 24 19:30:35 rockpro64 kernel: [  134.965663] blk_update_request: I/O error, dev sda, sector 72062128
Mar 24 19:30:35 rockpro64 kernel: [  134.966761] EXT4-fs warning (device sda2): ext4_end_bio:330: I/O error -5 writing to inode 12 (offset 75497472 size 8388608 starting block 9008128)
Mar 24 19:30:35 rockpro64 kernel: [  134.966783] Buffer I/O error on device sda2, logical block 619008
Mar 24 19:30:35 rockpro64 kernel: [  134.967496] Buffer I/O error on device sda2, logical block 619009
Mar 24 19:30:35 rockpro64 kernel: [  134.968197] Buffer I/O error on device sda2, logical block 619010
Mar 24 19:30:35 rockpro64 kernel: [  134.968897] Buffer I/O error on device sda2, logical block 619011
Mar 24 19:30:35 rockpro64 kernel: [  134.969596] Buffer I/O error on device sda2, logical block 619012
Mar 24 19:30:35 rockpro64 kernel: [  134.970296] Buffer I/O error on device sda2, logical block 619013
Mar 24 19:30:35 rockpro64 kernel: [  134.970996] Buffer I/O error on device sda2, logical block 619014
Mar 24 19:30:35 rockpro64 kernel: [  134.971694] Buffer I/O error on device sda2, logical block 619015
Mar 24 19:30:35 rockpro64 kernel: [  134.972392] Buffer I/O error on device sda2, logical block 619016
Mar 24 19:30:35 rockpro64 kernel: [  134.973092] Buffer I/O error on device sda2, logical block 619017
Mar 24 19:30:35 rockpro64 kernel: [  134.974679] EXT4-fs warning (device sda2): ext4_end_bio:330: I/O error -5 writing to inode 12 (offset 75497472 size 8388608 starting block 9008384)
Mar 24 19:30:35 rockpro64 kernel: [  134.975603] EXT4-fs warning (device sda2): ext4_end_bio:330: I/O error -5 writing to inode 12 (offset 75497472 size 8388608 starting block 9008640)
Mar 24 19:30:35 rockpro64 kernel: [  134.976498] EXT4-fs warning (device sda2): ext4_end_bio:330: I/O error -5 writing to inode 12 (offset 75497472 size 8388608 starting block 9008896)
Mar 24 19:30:35 rockpro64 kernel: [  134.977412] EXT4-fs warning (device sda2): ext4_end_bio:330: I/O error -5 writing to inode 12 (offset 75497472 size 8388608 starting block 9009152)
Mar 24 19:30:35 rockpro64 kernel: [  134.978329] EXT4-fs warning (device sda2): ext4_end_bio:330: I/O error -5 writing to inode 12 (offset 75497472 size 8388608 starting block 9009408)
Mar 24 19:30:35 rockpro64 kernel: [  134.979223] EXT4-fs warning (device sda2): ext4_end_bio:330: I/O error -5 writing to inode 12 (offset 83886080 size 8388608 starting block 9009664)
Mar 24 19:30:35 rockpro64 kernel: [  134.980106] EXT4-fs warning (device sda2): ext4_end_bio:330: I/O error -5 writing to inode 12 (offset 83886080 size 8388608 starting block 9009920)
Mar 24 19:30:35 rockpro64 kernel: [  134.981027] EXT4-fs warning (device sda2): ext4_end_bio:330: I/O error -5 writing to inode 12 (offset 83886080 size 8388608 starting block 9010176)
Mar 24 19:30:35 rockpro64 kernel: [  134.981939] EXT4-fs warning (device sda2): ext4_end_bio:330: I/O error -5 writing to inode 12 (offset 83886080 size 8388608 starting block 9010432)
Mar 24 19:30:35 rockpro64 kernel: [  134.986542] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x01 driverbyte=0x00
Mar 24 19:30:35 rockpro64 kernel: [  134.986593] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x2a 2a 00 04 4b 95 a0 00 00 f0 00
Mar 24 19:30:35 rockpro64 kernel: [  134.986634] blk_update_request: I/O error, dev sda, sector 72062368
Mar 24 19:30:36 rockpro64 kernel: [  135.628719] JBD2: Detected IO errors while flushing file data on sda2-8
Mar 24 19:30:36 rockpro64 kernel: [  135.628754] Aborting journal on device sda2-8.
Mar 24 19:30:36 rockpro64 kernel: [  135.629148] EXT4-fs (sda2): ext4_writepages: jbd2_start: 9223372036854775807 pages, ino 12; err -30
Mar 24 19:30:36 rockpro64 kernel: [  135.630113] JBD2: Error -5 detected when updating journal superblock for sda2-8.
Mar 24 19:30:36 rockpro64 kernel: [  135.630255] EXT4-fs error (device sda2): ext4_journal_check_start:56: Detected aborted journal
Mar 24 19:30:36 rockpro64 kernel: [  135.630258] EXT4-fs (sda2): Remounting filesystem read-only
Mar 24 19:30:36 rockpro64 kernel: [  135.630260] EXT4-fs (sda2): previous I/O error to superblock detected
Mar 24 19:30:36 rockpro64 kernel: [  135.630271] EXT4-fs error (device sda2) in ext4_da_write_end:2927: IO failure
Mar 24 19:30:36 rockpro64 kernel: [  135.630273] EXT4-fs (sda2): previous I/O error to superblock detected
Mar 24 19:30:36 rockpro64 kernel: [  135.646393] JBD2: Detected IO errors while flushing file data on sda2-8
Mar 24 19:31:01 rockpro64 CRON[946]: (root) CMD (for i in `pgrep "ftpd|nfsiod|smbd|afpd|cnid"` ; do ionice -c1 -p $i ${XU4_HMP_Fix}; done &>/dev/null)


anyone go any suggestions, if you want me to run any tests please let me know.

**Comment by tpoechtrager** [comment] 2019-03-24 20:13
USB 3.0 and USB-C is still borked. Use the latest mainline Kernel or - probably a better solution - a PCIE USB card.

**Comment by bullet64** [comment] 2019-03-24 20:39
No problem with the test.

`rock64@rockpro64:~$ time dd if=/dev/zero of=swap2g bs=1024 count=2097152
2097152+0 records in
2097152+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 13.889 s, 155 MB/s

real	0m13.900s
user	0m0.900s
sys	0m12.368s
`

Using
`rock64@rockpro64:~$ uname -a
Linux rockpro64 4.4.167-1161-rockchip-ayufan-g6f1664023387 #1 SMP Fri Mar 22 23:03:38 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
`

RP64v2.1, SSD on usb3.

**Comment by curiousercreative** [comment] 2019-05-01 14:15
I'm not 100% the cause of my problem is the same, but my rock64 USB3 is somewhat unreliable. System crashes unexpectedly during USB3 usage (5 hours into a large rsync for example).

Ubuntu: 18.04
Kernel: 4.4.167-1169-rockchip-ayufan-g3cde5c624c9c
Suspicious syslog entries: https://gist.github.com/curiousercreative/f2d62e434c2c23d664514de47d1f88e2

**Comment by marcosscriven** [comment] 2019-05-18 14:23
I'm getting instability and low speeds on USB3 with `stretch-openmediavault-rock64-0.8.0rc10-1125-arm64.img`

Kernel:

```
root@rock64:~# uname -a
Linux rock64 4.4.167-1181-rockchip-ayufan-gd20421e03128 #1 SMP Tue Apr 9 17:44:02 UTC 2019 aarch64 GNU/Linux
```

The errors I see:

```
[ 1558.961816] rockchip-vop ff370000.vop: [drm:vop_crtc_enable] Update mode to 3840x2160p60, type: 11
[ 1561.882330] rockchip-vop ff370000.vop: [drm:vop_crtc_enable] Update mode to 3840x2160p60, type: 11
[ 1624.903684] usb 5-1: new SuperSpeed USB device number 2 using xhci-hcd
[ 1624.972541] usb 5-1: New USB device found, idVendor=0781, idProduct=558c
[ 1624.972547] usb 5-1: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[ 1624.972552] usb 5-1: Product: Extreme SSD
[ 1624.972556] usb 5-1: Manufacturer: SanDisk
[ 1624.972560] usb 5-1: SerialNumber: 313831363833343030353134
[ 1625.011522] dwmmc_rockchip ff500000.dwmmc: Unexpected interrupt latency
[ 1625.043522] dwmmc_rockchip ff500000.dwmmc: Unexpected interrupt latency
[ 1625.063519] dwmmc_rockchip ff500000.dwmmc: Unexpected interrupt latency
[ 1625.079519] dwmmc_rockchip ff500000.dwmmc: Unexpected interrupt latency
[ 1625.084889] usbcore: registered new interface driver usb-storage
[ 1625.099521] dwmmc_rockchip ff500000.dwmmc: Unexpected interrupt latency
[ 1625.104215] scsi host0: uas
[ 1625.104648] usbcore: registered new interface driver uas
[ 1625.105475] scsi 0:0:0:0: Direct-Access     SanDisk  Extreme SSD      1012 PQ: 0 ANSI: 6
[ 1625.106957] scsi 0:0:0:1: Enclosure         SanDisk  SES Device       1012 PQ: 0 ANSI: 6
[ 1625.108630] sd 0:0:0:0: [sda] Spinning up disk...
[ 1626.111555] .ready
[ 1626.127831] sd 0:0:0:0: [sda] 488396800 512-byte logical blocks: (250 GB/233 GiB)
[ 1626.127838] sd 0:0:0:0: [sda] 4096-byte physical blocks
[ 1626.128608] sd 0:0:0:0: [sda] Write Protect is off
[ 1626.128615] sd 0:0:0:0: [sda] Mode Sense: 67 00 10 08
[ 1626.128880] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, supports DPO and FUA
[ 1626.129026] xhci-hcd xhci-hcd.9.auto: ERROR Transfer event for disabled endpoint slot 1 ep 2 or incorrect stream ring
[ 1626.129033] xhci-hcd xhci-hcd.9.auto: @00000000f4cf55c0 00000000 00000000 1b000000 01038001
[ 1626.146348] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, supports DPO and FUA
[ 1626.146454] sd 0:0:0:0: [sda] Attached SCSI disk
[ 1703.567919] systemd[1]: apt-daily.timer: Adding 59min 7.762977s random time.
[ 1704.015011] systemd[1]: apt-daily.timer: Adding 5h 49min 22.785356s random time.
[ 1704.313660] systemd[1]: apt-daily.timer: Adding 11h 11min 23.493945s random time.
[ 1704.689408] systemd[1]: apt-daily.timer: Adding 6h 13min 38.243589s random time.
[ 1705.989820] systemd[1]: apt-daily.timer: Adding 3h 41min 31.588168s random time.
[ 1706.418237] systemd[1]: apt-daily.timer: Adding 1h 29min 22.719973s random time.
[ 1706.718957] systemd[1]: apt-daily.timer: Adding 3h 48min 8.743877s random time.
[ 1707.293635] systemd[1]: apt-daily.timer: Adding 9h 23min 31.712494s random time.
[ 1731.619569] EXT4-fs (sda): recovery complete
[ 1731.636883] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: (null)
[ 1735.031742] xhci-hcd xhci-hcd.9.auto: ERROR Transfer event for disabled endpoint slot 1 ep 3 or incorrect stream ring
[ 1735.049441] xhci-hcd xhci-hcd.9.auto: @00000000f4cf5450 00000000 00000000 1b000000 01048000
```

**Comment by whirm** [comment] 2019-05-19 13:11
> [ 1735.031742] xhci-hcd xhci-hcd.9.auto: ERROR Transfer event for disabled endpoint slot 1 ep 3 or incorrect stream ring

I have the same issues with a WD backup plus slim self-powered external disk (using Asmedia ASM1153 controller).

With an externally powered 4 bay enclosure (JMicron JMS567 controller) everything is fine.

**Comment by ayufan** [comment] 2019-06-26 21:02
This seems to be duplicate of https://github.com/ayufan-rock64/linux-build/issues/112

**Closed by ayufan** 2019-06-26 21:02 UTC
