### ISSUE TITLE
Crash with Illegal Instruction in Systemd when rebooting from within system

### ISSUE THREAD

**Issue by interfect** [ayufan-rock64/linux-build#110] opened 2018-02-25 17:31 UTC
I installed xenial-minimal-rock64-0.6.22-188-arm64.img.xz on my Rock64, then booted it up and did an `apt update` and `apt upgrade` (as well as attempting to install MATE).

The next reboot gave me an error in the console, just after setting the hostname, and the boot process stopped:

```
systemd-gpt-aut[268]: undefined instruction: pc=00000055937bc498
Code: d2800004 b9000001 17ffffe7 00000000 (a9bd7bfd)
```

A reboot with the reset button seems to have allowed the system to boot properly.

**Comment by interfect** [comment] 2018-02-25 22:34
I've updated the title after working with it for a bit more. Every time I reboot with the reset switch it comes up fine, and every time I reboot from the GUI or CLI it crashes on the next boot.

**Comment by xalius** [comment] 2018-03-30 11:10
This shoudl be a duplicate of #101

**Closed by xalius** 2018-03-30 11:10 UTC
Labels: duplicate
