### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by SloCompTech** [ayufan-rock64/linux-build#251] opened 2018-07-25 18:40 UTC
When I try to update to latest version I get
```
Unpacking u-boot-rockchip-rock64 (2017.09-rockchip-ayufan-1017-g7bd50d7e0f) ...
dpkg: error processing archive /var/cache/apt/archives/u-boot-rockchip-rock64_2017.09-rockchip-ayufan-1017-g7bd50d7e0f_all.deb (--unpack):
 trying to overwrite '/usr/local/sbin/rock64_upgrade_bootloader.sh', which is also in package u-boot-rock64 0.6.44
Errors were encountered while processing:
 /var/cache/apt/archives/u-boot-rockchip-rock64_2017.09-rockchip-ayufan-1017-g7bd50d7e0f_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by ayufan** [comment] 2018-07-25 20:47
Duplicate of: https://github.com/ayufan-rock64/linux-build/issues/251

**Closed by ayufan** 2018-07-25 20:47 UTC
